version: '3.7'
services:
  api:
    build: .
    container_name: sermov-api-container
    depends_on:
      - postgres
    volumes:
      - .:/code
    ports:
      - 80:80
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5437:5432"
    environment:
      - POSTGRES_USER=sermovuser
      - POSTGRES_PASSWORD=sermovpassword
      - POSTGRES_DB=sermovpostgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      # copy the sql script to fill tables
      - ./sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
volumes:
  postgres_data: